numero = int(input('digite um numero de 1 - 12 para ver\nsua correspondencia com os meses do ano: '))
if numero == 1 : print('janeiro')
if numero == 2 : print('fevereiro')
if numero == 3 : print('março')
if numero == 4 : print('abril')
if numero == 5 : print('maio')
if numero == 6 : print('junho')
if numero == 7 : print('julho')
if numero == 8 : print('setembro')
if numero == 9 : print('setembro')
if numero == 10 : print('outubro')
if numero == 11 : print('novembro')
if numero == 12 : print('dezembro')
if numero > 12 or numero < 1 : print('mes inexistente')