numero = int(input('digite um numero de 1 - 7 para ver\nsua correspondencia com o dia da semana: '))
if numero == 1 : print('domingo')
if numero == 2 : print('segunda')
if numero == 3 : print('terca')
if numero == 4 : print('quarta')
if numero == 5 : print('quinta')
if numero == 6 : print('sexta')
if numero == 7 : print('sabado')
if numero > 7 or numero < 1 : print('dia inexistente')